site_name: Hardening Brave Browser — Network Pro™
site_url: https://brave.netwk.pro
repo_url: https://github.com/netwk-pro/hardening-brave/
repo_name: GitHub
docs_dir: src
site_dir: build/

theme:
  name: material
  language: en
  font:
    text: null
    code: null
  logo: img/icon-512x512.png
  favicon: img/favicon.svg
  palette:
    # Palette toggle for automatic mode
    # Default to dark mode
    - scheme: slate
      primary: deep orange
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Optional light mode
    - scheme: default
      primary: deep orange
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest

plugins:
  - privacy:
      assets: true
      assets_fetch: true

markdown_extensions:
  - admonition
  - pymdownx.details # Enables `???` collapsibles
  - pymdownx.superfences # Optional but recommended for nested blocks

extra:
  base_url: /
  social:
    - icon: fontawesome/brands/instagram
      name: Network Pro on Instagram
      link: https://instagram.com/netwk_pro
    - icon: fontawesome/brands/facebook
      name: Network Pro on Facebook
      link: https://facebook.com/neteng.pro
    - icon: fontawesome/brands/linkedin
      name: Network Pro on LinkedIn
      link: https://linkedin.com/company/netwk-pro
    - icon: fontawesome/brands/mastodon
      name: Network Pro on Mastodon
      link: https://noc.social/@neteng_pro
    - icon: fontawesome/brands/discord
      name: Network Pro on Discord
      link: https://discord.neteng.pro
    - icon: fontawesome/solid/at
      name: Contact Us
      link: https://netwk.pro/contact

copyright: >
  Copyright &copy; 2025 Network Pro Strategies (Network Pro&trade;) – This blog
  does not use cookies. See our <a href="https://netwk.pro/privacy">Privacy
  Policy</a> for details.

nav:
  - Hardening Brave: index.md
  - Website: https://netwk.pro
  - Blog: https://blog.netwk.pro
  - Privacy Apps: https://apps.netwk.pro
# cspell:ignore collapsibles pymdownx superfences
